In [18]:
import numpy as np
import matplotlib.pyplot as plt

from modules.game import Game
from modules.node import CongklakNode
from modules.state import CongklakState
from modules.strategies import (
    simple_strategy,
    random_strategy,
    maximize_house_strategy,
    get_max_diff
)

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [24]:
player = 0
state = CongklakState(player=player, holes=3, init_beads=3)
state

Player: 0, board:
[[0 3 3 3]
 [0 3 3 3]]

In [25]:
state = state.action(1)
state

Player: 1, board:
[[2 0 4 4]
 [0 0 4 4]]

In [26]:
state = state.auto('max_diff')
state

Player: 0, board:
[[2 0 6 1]
 [1 1 1 6]]

In [28]:
state = state.action(3)
state

Player: 1, board:
[[3 1 7 1]
 [1 1 3 1]]

In [29]:
state = state.auto('max_diff')
state

Player: 0, board:
[[3 0 0 2]
 [7 0 1 5]]