In [2]:
import numpy as np
import matplotlib.pyplot as plt

from modules.game import Game
from modules.node import CongklakNode
from modules.state import CongklakState
from modules.strategies import (
    simple_strategy,
    random_strategy,
    maximize_house_strategy,
    get_max_diff
)

%load_ext autoreload
%autoreload 2

In [4]:
player = 0
state = CongklakState(player=player, holes=7, init_beads=7)
state

Player: 0, board:
[[0 7 7 7 7 7 7 7]
 [0 7 7 7 7 7 7 7]]

In [5]:
state = state.action(7)
state

Player: 1, board:
[[2 8 8 8 8 8 8 0]
 [0 8 8 8 8 8 8 0]]